**TRATAMENTO DE DADOS DO TCC**

Carregando os dados do histórico de negociação do Minicontrato futuro do índice Bovespa que vai do dia 14-03 a 12-04

In [ ]:
import pandas as pd
col_names = [
    "Time",
    "Delta",
    "Vol.Compra",
    "Vol.Venda",
    "Percentual100u",
    "Vol.TotalC",
    "Vol.Negócios",
    "Preço",
    "status",
    "MédiaMóvel21",
    "BBollingerS2",
    "BBollingerI2"
]
for i in range(13, 33):
    col_names.append(f"ASK{i-12}")
for i in range(33, 53):
    col_names.append(f"BID{i-32}")

df = pd.DataFrame(pd.read_csv('data.csv',sep='\t', header=None))
df.columns = col_names
df.head()

,Time,Delta,Vol.Compra,Vol.Venda,Percentual100u,Vol.TotalC,Vol.Negócios,Preço,status,MédiaMóvel21,...,BID11,BID12,BID13,BID14,BID15,BID16,BID17,BID18,BID19,BID20
0,2024.03.14 13:47:12,-6022,3271,9293,42,12569,753,128675,inativo,128768,...,1664,1581,1445,1877,4986,1578,1311,1246,1305,1869
1,2024.03.14 13:47:13,-6052,3347,9399,38,12747,791,128670,inativo,128768,...,1666,1578,1450,1853,4987,1573,1303,1248,1305,1869
2,2024.03.14 13:47:14,-6047,3416,9463,42,12884,826,128670,inativo,128768,...,1667,1635,1453,1918,4985,1544,1298,1242,1309,1869
3,2024.03.14 13:47:15,-6043,3496,9539,46,13045,868,128675,inativo,128768,...,1670,1637,1457,1912,4989,1519,1319,1240,1308,1869
4,2024.03.14 13:47:16,-5634,3946,9580,79,13527,896,128675,inativo,128768,...,1659,1607,1419,1939,4989,1493,1216,1225,1313,1868

Conferindo a quantidade de dados por dia

In [ ]:
df['Time'] = pd.to_datetime(df['Time'])
def show_linhas_dia(df):
  linhas_por_dia = df.groupby(df['Time'].dt.date).size().reset_index(name='quantidade_de_linhas')
  print(linhas_por_dia)
show_linhas_dia(df)

          Time  quantidade_de_linhas
0   2024-03-14                 13427
1   2024-03-15                 30359
2   2024-03-18                 30360
3   2024-03-19                 30360
4   2024-03-20                 30345
5   2024-03-21                 30343
6   2024-03-22                 30359
7   2024-03-25                 30356
8   2024-03-26                 28836
9   2024-03-27                 30359
10  2024-03-28                 30358
11  2024-04-01                 30300
12  2024-04-02                 30282
13  2024-04-03                 30287
14  2024-04-04                 30359
15  2024-04-05                 30306
16  2024-04-08                 29226
17  2024-04-09                 30321
18  2024-04-10                 30334
19  2024-04-11                 30320
20  2024-04-12                 30349

Verificando o horário da primeira e última negociação do dia

In [ ]:
def inicio_fim_negocia_dia(df):
  primeira_linha_por_dia = df.groupby(df['Time'].dt.date).first()
  ultima_linha_por_dia = df.groupby(df['Time'].dt.date).last()
  print("Primeira:")
  print(primeira_linha_por_dia['Time'])
  print("Última:")
  print(ultima_linha_por_dia['Time'])
inicio_fim_negocia_dia(df)

Primeira:
Time
2024-03-14   2024-03-14 13:47:12
2024-03-15   2024-03-15 09:05:01
2024-03-18   2024-03-18 09:05:01
2024-03-19   2024-03-19 09:05:01
2024-03-20   2024-03-20 09:05:02
2024-03-21   2024-03-21 09:05:02
2024-03-22   2024-03-22 09:05:01
2024-03-25   2024-03-25 09:05:02
2024-03-26   2024-03-26 09:05:02
2024-03-27   2024-03-27 09:05:01
2024-03-28   2024-03-28 09:05:01
2024-04-01   2024-04-01 09:05:02
2024-04-02   2024-04-02 09:05:02
2024-04-03   2024-04-03 09:05:02
2024-04-04   2024-04-04 09:05:02
2024-04-05   2024-04-05 09:05:02
2024-04-08   2024-04-08 09:05:01
2024-04-09   2024-04-09 09:05:02
2024-04-10   2024-04-10 09:05:02
2024-04-11   2024-04-11 09:05:02
2024-04-12   2024-04-12 09:05:01
Name: Time, dtype: datetime64[ns]
Última:
Time
2024-03-14   2024-03-14 17:31:00
2024-03-15   2024-03-15 17:31:00
2024-03-18   2024-03-18 17:31:00
2024-03-19   2024-03-19 17:31:00
2024-03-20   2024-03-20 17:31:01
2024-03-21   2024-03-21 17:31:01
2024-03-22   2024-03-22 17:31:00
2024-03-25   2024-03-25 17:31:01
2024-03-26   2024-03-26 17:31:00
2024-03-27   2024-03-27 17:31:00
2024-03-28   2024-03-28 17:31:00
2024-04-01   2024-04-01 17:31:01
2024-04-02   2024-04-02 17:31:00
2024-04-03   2024-04-03 17:31:00
2024-04-04   2024-04-04 17:31:00
2024-04-05   2024-04-05 17:31:00
2024-04-08   2024-04-08 17:31:00
2024-04-09   2024-04-09 17:31:01
2024-04-10   2024-04-10 17:31:01
2024-04-11   2024-04-11 17:31:01
2024-04-12   2024-04-12 17:31:00
Name: Time, dtype: datetime64[ns]

Removendo o dia 14-03-2024 devido a falta de dados e padronizando o horário das negociações, irá de 09:06:00 à 17:31:00

In [ ]:
df = df = df[~((df['Time'].dt.day == 14) & (df['Time'].dt.month == 3) & (df['Time'].dt.year == 2024))]
df = df.reset_index(drop=True)
from datetime import datetime
hora_inicio = datetime.strptime('09:06:00', '%H:%M:%S').time()
hora_fim = datetime.strptime('17:31:00', '%H:%M:%S').time()
df = df[(df['Time'].dt.time >= hora_inicio) & (df['Time'].dt.time <= hora_fim)]

inicio_fim_negocia_dia(df)

Primeira:
Time
2024-03-15   2024-03-15 09:06:00
2024-03-18   2024-03-18 09:06:00
2024-03-19   2024-03-19 09:06:00
2024-03-20   2024-03-20 09:06:00
2024-03-21   2024-03-21 09:06:00
2024-03-22   2024-03-22 09:06:00
2024-03-25   2024-03-25 09:06:00
2024-03-26   2024-03-26 09:06:00
2024-03-27   2024-03-27 09:06:00
2024-03-28   2024-03-28 09:06:00
2024-04-01   2024-04-01 09:06:00
2024-04-02   2024-04-02 09:06:01
2024-04-03   2024-04-03 09:06:01
2024-04-04   2024-04-04 09:06:00
2024-04-05   2024-04-05 09:06:00
2024-04-08   2024-04-08 09:06:00
2024-04-09   2024-04-09 09:06:00
2024-04-10   2024-04-10 09:06:00
2024-04-11   2024-04-11 09:06:00
2024-04-12   2024-04-12 09:06:00
Name: Time, dtype: datetime64[ns]
Última:
Time
2024-03-15   2024-03-15 17:31:00
2024-03-18   2024-03-18 17:31:00
2024-03-19   2024-03-19 17:31:00
2024-03-20   2024-03-20 17:31:00
2024-03-21   2024-03-21 17:30:59
2024-03-22   2024-03-22 17:31:00
2024-03-25   2024-03-25 17:31:00
2024-03-26   2024-03-26 17:31:00
2024-03-27   2024-03-27 17:31:00
2024-03-28   2024-03-28 17:31:00
2024-04-01   2024-04-01 17:31:00
2024-04-02   2024-04-02 17:31:00
2024-04-03   2024-04-03 17:31:00
2024-04-04   2024-04-04 17:31:00
2024-04-05   2024-04-05 17:31:00
2024-04-08   2024-04-08 17:31:00
2024-04-09   2024-04-09 17:31:00
2024-04-10   2024-04-10 17:31:00
2024-04-11   2024-04-11 17:31:00
2024-04-12   2024-04-12 17:31:00
Name: Time, dtype: datetime64[ns]

Verificando e removendo duplicatas

In [ ]:
duplicatas = df['Time'].duplicated().sum()
print(f"Número de duplicatas: {duplicatas}")

if duplicatas > 0:
    df = df.drop_duplicates(subset='Time')

print(f"Número atualizado de registros após remover duplicatas: {len(df)}")
show_linhas_dia(df)

Número de duplicatas: 27542
Número atualizado de registros após remover duplicatas: 575399
          Time  quantidade_de_linhas
0   2024-03-15                 30237
1   2024-03-18                 30031
2   2024-03-19                 30289
3   2024-03-20                 29805
4   2024-03-21                 29394
5   2024-03-22                 30180
6   2024-03-25                 30098
7   2024-03-26                 28697
8   2024-03-27                 30162
9   2024-03-28                 30205
10  2024-04-01                 27331
11  2024-04-02                 23925
12  2024-04-03                 24222
13  2024-04-04                 29358
14  2024-04-05                 29012
15  2024-04-08                 25593
16  2024-04-09                 28823
17  2024-04-10                 29355
18  2024-04-11                 28531
19  2024-04-12                 30151

Preparação para interpolação, para preencher os dados faltantes

In [ ]:
def gerar_df_vazio(i, f):
  # Criando um intervalo de datas
  datas = pd.date_range(start=i, end=f, freq='D')

  # Criando um DataFrame vazio
  df_completo = pd.DataFrame()

  # Preenchendo o DataFrame com todos os segundos de cada dia
  for data in datas:
      # Gerando todos os segundos entre 09:06:00 e 17:30:00
      timestamps = pd.date_range(start=data.strftime('%Y-%m-%d') + ' 09:06:00',
                                end=data.strftime('%Y-%m-%d') + ' 17:31:00', freq='S')
      # Concatenando os timestamps ao DataFrame completo
      df_completo = pd.concat([df_completo, pd.DataFrame({'Time': timestamps})])
  return df_completo

In [ ]:
semana1 = gerar_df_vazio('2024-03-15', '2024-03-15')
semana2 = gerar_df_vazio('2024-03-18', '2024-03-22')
semana3 = gerar_df_vazio('2024-03-25', '2024-03-28')
semana4 = gerar_df_vazio('2024-04-01', '2024-04-05')
semana5 = gerar_df_vazio('2024-04-08', '2024-04-12')
df_completo = pd.concat([semana1, semana2,semana3,semana4,semana5])
show_linhas_dia(df_completo)
# Resetando o índice
df_completo.reset_index(drop=True, inplace=True)
df_completo.index += 1

show_linhas_dia(df_completo)

          Time  quantidade_de_linhas
0   2024-03-15                 30301
1   2024-03-18                 30301
2   2024-03-19                 30301
3   2024-03-20                 30301
4   2024-03-21                 30301
5   2024-03-22                 30301
6   2024-03-25                 30301
7   2024-03-26                 30301
8   2024-03-27                 30301
9   2024-03-28                 30301
10  2024-04-01                 30301
11  2024-04-02                 30301
12  2024-04-03                 30301
13  2024-04-04                 30301
14  2024-04-05                 30301
15  2024-04-08                 30301
16  2024-04-09                 30301
17  2024-04-10                 30301
18  2024-04-11                 30301
19  2024-04-12                 30301
          Time  quantidade_de_linhas
0   2024-03-15                 30301
1   2024-03-18                 30301
2   2024-03-19                 30301
3   2024-03-20                 30301
4   2024-03-21                 30301
5   2024-03-22                 30301
6   2024-03-25                 30301
7   2024-03-26                 30301
8   2024-03-27                 30301
9   2024-03-28                 30301
10  2024-04-01                 30301
11  2024-04-02                 30301
12  2024-04-03                 30301
13  2024-04-04                 30301
14  2024-04-05                 30301
15  2024-04-08                 30301
16  2024-04-09                 30301
17  2024-04-10                 30301
18  2024-04-11                 30301
19  2024-04-12                 30301

Realizando a interpolação de dados

In [ ]:
df_completo = pd.merge(df_completo, df, on="Time", how="left")
for coluna in df_completo.columns[1:]:
    df_completo[coluna] = df_completo[coluna].interpolate(method='linear')
show_linhas_dia(df_completo)

          Time  quantidade_de_linhas
0   2024-03-15                 30301
1   2024-03-18                 30301
2   2024-03-19                 30301
3   2024-03-20                 30301
4   2024-03-21                 30301
5   2024-03-22                 30301
6   2024-03-25                 30301
7   2024-03-26                 30301
8   2024-03-27                 30301
9   2024-03-28                 30301
10  2024-04-01                 30301
11  2024-04-02                 30301
12  2024-04-03                 30301
13  2024-04-04                 30301
14  2024-04-05                 30301
15  2024-04-08                 30301
16  2024-04-09                 30301
17  2024-04-10                 30301
18  2024-04-11                 30301
19  2024-04-12                 30301

Retirando apenas a coluna de tempo e preço, onde a de tempo será usada para possível manipulação de dados e a de preço será usada para simular as operações de compra

In [ ]:
df_completo.head()

,Time,Delta,Vol.Compra,Vol.Venda,Percentual100u,Vol.TotalC,Vol.Negócios,Preço,status,MédiaMóvel21,...,BID11,BID12,BID13,BID14,BID15,BID16,BID17,BID18,BID19,BID20
0,2024-03-15 09:06:00,-6635.0,484.0,7119.0,21.0,7605.0,345.0,128760.0,vendido,128939.0,...,628.0,1254.0,536.0,744.0,465.0,849.0,707.0,675.0,640.0,883.0
1,2024-03-15 09:06:01,-6688.0,1425.0,8113.0,45.0,9545.0,518.0,128765.0,vendido,128939.0,...,682.0,637.0,1251.0,568.0,749.0,461.0,855.0,749.0,727.0,815.0
2,2024-03-15 09:06:02,-7026.0,2096.0,9122.0,32.0,11224.0,656.0,128755.0,vendido,128939.0,...,1253.0,562.0,726.0,455.0,851.0,747.0,660.0,798.0,894.0,1486.0
3,2024-03-15 09:06:03,-7879.0,2479.0,10358.0,28.0,12838.0,772.0,128750.0,vendido,128939.0,...,455.0,847.0,722.0,660.0,802.0,894.0,1486.0,1011.0,727.0,802.0
4,2024-03-15 09:06:04,-6962.0,3493.0,10455.0,91.0,13959.0,877.0,128770.0,vendido,128939.0,...,706.0,623.0,1212.0,557.0,732.0,433.0,849.0,801.0,653.0,789.0

In [ ]:
df_preco = pd.DataFrame()
df_preco["Time"] = df_completo["Time"]
df_preco["Preço"] = df_completo["Preço"]
df_preco.head()

                 Time     Preço
0 2024-03-15 09:06:00  128760.0
1 2024-03-15 09:06:01  128765.0
2 2024-03-15 09:06:02  128755.0
3 2024-03-15 09:06:03  128750.0
4 2024-03-15 09:06:04  128770.0

Exportando dados já tratados

In [ ]:
df_preco.to_csv('df_preco.csv', index=False)

**TCC**

CONTINUA A PARTIR DE: "Removendo o dia 14-03-2024 devido a falta de dados e padronizando o horário das negociações, irá de 09:06:00 à 17:31:00"

In [ ]:
# Definir o intervalo de datas
start_date = '2024-03-15'
end_date = '2024-03-22'

# Filtrar o DataFrame para o intervalo de datas
filtered_df = df[(df['Time'] >= start_date) & (df['Time'] <= end_date)]

In [ ]:
duplicatas = filtered_df['Time'].duplicated().sum()
print(f"Número de duplicatas: {duplicatas}")

if duplicatas > 0:
    filtered_df = filtered_df.drop_duplicates(subset='Time')

print(f"Número atualizado de registros após remover duplicatas: {len(filtered_df)}")
show_linhas_dia(filtered_df)

Número de duplicatas: 1716
Número atualizado de registros após remover duplicatas: 149756
         Time  quantidade_de_linhas
0  2024-03-15                 30237
1  2024-03-18                 30031
2  2024-03-19                 30289
3  2024-03-20                 29805
4  2024-03-21                 29394

In [ ]:
def gerar_df_vazio(i, f):
  # Criando um intervalo de datas
  datas = pd.date_range(start=i, end=f, freq='D')

  # Criando um DataFrame vazio
  df_completo = pd.DataFrame()

  # Preenchendo o DataFrame com todos os segundos de cada dia
  for data in datas:
      # Gerando todos os segundos entre 09:06:00 e 17:30:00
      timestamps = pd.date_range(start=data.strftime('%Y-%m-%d') + ' 09:06:00',
                                end=data.strftime('%Y-%m-%d') + ' 17:31:00', freq='S')
      # Concatenando os timestamps ao DataFrame completo
      df_completo = pd.concat([df_completo, pd.DataFrame({'Time': timestamps})])
  return df_completo

In [ ]:
semana1 = gerar_df_vazio('2024-03-15', '2024-03-15')
semana2 = gerar_df_vazio('2024-03-18', '2024-03-22')

<ipython-input-7-5272dac001bc>:11: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  timestamps = pd.date_range(start=data.strftime('%Y-%m-%d') + ' 09:06:00',
<ipython-input-7-5272dac001bc>:11: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  timestamps = pd.date_range(start=data.strftime('%Y-%m-%d') + ' 09:06:00',

In [ ]:
df_completo = pd.concat([semana1, semana2])
show_linhas_dia(df_completo)
# Resetando o índice
df_completo.reset_index(drop=True, inplace=True)
df_completo.index += 1

show_linhas_dia(df_completo)

         Time  quantidade_de_linhas
0  2024-03-15                 30301
1  2024-03-18                 30301
2  2024-03-19                 30301
3  2024-03-20                 30301
4  2024-03-21                 30301
5  2024-03-22                 30301
         Time  quantidade_de_linhas
0  2024-03-15                 30301
1  2024-03-18                 30301
2  2024-03-19                 30301
3  2024-03-20                 30301
4  2024-03-21                 30301
5  2024-03-22                 30301

In [ ]:
df_completo = pd.merge(df_completo, filtered_df, on="Time", how="left")
for coluna in df_completo.columns[1:]:
    df_completo[coluna] = df_completo[coluna].interpolate(method='linear')
show_linhas_dia(df_completo)

<ipython-input-10-1a80f8166590>:3: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_completo[coluna] = df_completo[coluna].interpolate(method='linear')

         Time  quantidade_de_linhas
0  2024-03-15                 30301
1  2024-03-18                 30301
2  2024-03-19                 30301
3  2024-03-20                 30301
4  2024-03-21                 30301
5  2024-03-22                 30301

In [ ]:
len(df_completo)

181806

In [ ]:
df_preco = pd.DataFrame()
df_preco["Time"] = df_completo["Time"]
df_preco["Preço"] = df_completo["Preço"]
df_preco.head()

                 Time     Preço
0 2024-03-15 09:06:00  128760.0
1 2024-03-15 09:06:01  128765.0
2 2024-03-15 09:06:02  128755.0
3 2024-03-15 09:06:03  128750.0
4 2024-03-15 09:06:04  128770.0

In [ ]:
df_preco.to_csv('df_precoTCC.csv', index=False)